# Generated by Django 5.2.11 on 2026-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='display_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
